# Generated by Django 2.1.2 on 2018-10-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diceset',
            name='description',
            field=models.CharField(default='this is the default description', max_length=200),
            preserve_default=False,
        ),
    ]
